### ISSUE TITLE
ModuleNotFoundError: No module named 'blink.streams'

### ISSUE THREAD

**Issue by fugkco** [flathub/com.icanblink.blink#3]
I dunno what's happening, but it won't work when running it:
```
$ flatpak run com.icanblink.blink
Traceback (most recent call last):
  File "/app/bin/blink", line 67, in <module>
    from blink import Blink
  File "/app/lib/python3.9/site-packages/blink/__init__.py", line 31, in <module>
    from blink.chatwindow import ChatWindow
  File "/app/lib/python3.9/site-packages/blink/chatwindow.py", line 41, in <module>
    from blink.contacts import URIUtils
  File "/app/lib/python3.9/site-packages/blink/contacts.py", line 48, in <module>
    from blink.sessions import SessionManager, StreamDescription
  File "/app/lib/python3.9/site-packages/blink/sessions.py", line 55, in <module>
    from blink.streams.message import MessageStream
ModuleNotFoundError: No module named 'blink.streams'
```

**Comment by automatyck** [comment]
I am experiencing the same error on with Blink flatpak version 5.1.8 on Fedora 36.
